In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import pickle
import joblib

%matplotlib inline

plt.style.use('ggplot')
mpl.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'NanumGothic'

In [3]:
# pixel 데이터 로드
chery_df = pd.read_csv("./data/real_weight.csv")
chery_df.shape

(10, 10)

In [5]:
chery_df

,Unnamed: 0,times2,no_distortion_pixel_mean,no_distortion_count,distortion_pixel_mean,distortion_count,total_mean,total_count,timess,real_weight
0,0,20210823,1973.000000,9.000000,2077.000000,3.666667,1997.666667,12.666667,2.021082e+13,378.0
1,1,20210830,2573.000000,33.000000,2671.333333,7.000000,2594.333333,40.000000,2.021083e+13,556.0
2,2,20210905,3320.333333,34.000000,3446.333333,6.000000,3340.000000,40.000000,2.021091e+13,827.0
3,3,20210913,4714.333333,27.666667,5288.000000,8.000000,4840.000000,35.666667,2.021091e+13,1093.0
4,4,20210920,5857.333333,24.000000,6161.666667,6.000000,5918.000000,30.000000,2.021092e+13,1272.0
5,5,20210927,6440.333333,18.333333,6964.666667,3.333333,6529.000000,21.666667,2.021093e+13,1379.0
6,6,20211004,6657.000000,19.666667,6980.333333,5.333333,6749.000000,25.000000,2.021100e+13,1553.0
7,7,20211011,8111.000000,12.666667,8693.000000,5.000000,8277.333333,17.666667,2.021101e+13,1715.0
8,8,20211018,7688.000000,12.000000,10240.000000,4.000000,7956.000000,16.000000,2.021102e+13,1787.0
9,9,20211025,8350.000000,19.666667,9630.000000,4.333333,8577.666667,24.000000,2.021103e+13,1929.0

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(chery_df[['no_distortion_pixel_mean']], chery_df['real_weight'], test_size=0.3, random_state=1)

lr = LinearRegression()
lr.fit(X_train, y_train)

#saved_model = pickle.dumps(lr)
joblib.dump(lr, './chery_linear_model.pkl')

y_preds = lr.predict(X_test)
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)

print('MSE : {0: .3f}, RMSE : {1:.3F}'.format(mse, rmse))
print('Variance score : {0:.3f}'.format(r2_score(y_test, y_preds)))

print('절편 값:', lr.intercept_)
print('회귀 계수값:', np.round(lr.coef_, 1))

MSE :  9018.031, RMSE : 94.963
Variance score : 0.957
절편 값: -31.120920485775287
회귀 계수값: [0.2]

In [2]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import pickle
import glob

if __name__ == '__main__':

    raw_df = pd.read_csv(glob.glob('./data/real_weight.csv')[0])
    raw_df

    X, y = raw_df[['no_distortion_pixel_mean']], raw_df['real_weight']
    line_fitter = LinearRegression()
    line_fitter.fit(X, y)

    with open('chery_linear_model.pkl', 'wb') as f:
        pickle.dump(line_fitter, f)