In [3]:
import numpy as np
import pandas as pd

### 11월 ~ 19일 평균 픽셀

In [139]:
# pixel 데이터 로드
df_jetson = pd.read_csv("./csv/jetson_11_12~11_19.csv")
df_jetson.shape

(2240, 5)

In [140]:
#df_total['time'] = pd.to_datetime(df_total['create_time'], infer_datetime_format=False)
df_jetson

,date,org_file_name,weight_prediction_pixel_mean,weight_prediction_weight,bright
0,20211114085254,FA0002_GW01_H01_0001_20211114085254_farm_image...,9581.25,2157.2,yes
1,20211114133237,FA0002_GW01_H02_0013_20211114133237_farm_image...,10150.00,2286.0,yes
2,20211114122637,FA0002_GW01_H02_0012_20211114122637_farm_image...,9718.75,2188.3,yes
3,20211114134243,FA0002_GW01_H02_0013_20211114134243_farm_image...,10806.25,2434.5,yes
4,20211114104233,FA0002_GW01_H01_0002_20211114104233_farm_image...,8875.00,1997.4,yes
...,...,...,...,...,...
2235,20211117144434,FA0002_GW01_H02_0010_20211117144434_farm_image...,7887.50,1773.8,yes
2236,20211117121851,FA0002_GW01_H01_0001_20211117121851_farm_image...,8312.50,1870.0,no
2237,20211117150633,FA0002_GW01_H02_0010_20211117150633_farm_image...,6468.75,1452.7,yes
2238,20211117111636,FA0002_GW01_H02_0010_20211117111636_farm_image...,7031.25,1580.0,yes
2239,20211117133937,FA0002_GW01_H01_0001_20211117133937_farm_image...,9337.50,2102.0,no

In [101]:
# drop null
df_jetson = df_jetson[~df_jetson.weight_prediction_pixel_mean.isnull()]
df_jetson['date'] = df_jetson['date'].astype(str)
df_jetson['date'] = pd.to_datetime(df_jetson['date'])
#df_jetson['date'] = df_jetson['date'].dt.tz_localize('UTC')

target_day = 19
df_jetson_19 = df_jetson.query('date.dt.day == @target_day')
#df_jetson['2020-10-12 09:04:31']
# query = (df_db['date']=='2021-11-25')
# df_db = df_db.loc[query]
# drop outlier
#df_total = df_total[df_total.weight_prediction_pixel_mean < 12000]

In [102]:
#df_total.groupby(pd.Grouper(key='create_time' ,freq='1h')).mean()
df_jetson_19.groupby(pd.Grouper(key='bright')).mean()

        weight_prediction_pixel_mean  weight_prediction_weight
bright
no                       9944.015957               2239.333333
yes                      9043.229167               2035.436806

### 11월 19일 ~ 11월 25일 평균 픽셀

In [110]:
# pixel 데이터 로드
df_db = pd.read_csv("./csv/11_19~11_25~.csv")
df_db.shape
df_db

,org_file_name,bright,create_time,farm_id,house_id,module_id,weight_prediction_count,weight_prediction_pixel_mean,weight_prediction_weight,weight_prediction_status
0,FA0002_GW01_H01_0001_20211119081826_farm_image...,yes,2021-11-19 08:18:26,FA0002,H01,1,2.0,7789.0,1719.8,success
1,FA0002_GW01_H01_0001_20211119083838_farm_image...,yes,2021-11-19 08:38:38,FA0002,H01,1,3.0,8957.0,1982.4,success
2,FA0002_GW01_H01_0001_20211119084842_farm_image...,yes,2021-11-19 08:48:42,FA0002,H01,1,1.0,7488.0,1652.2,success
3,FA0002_GW01_H01_0001_20211119085847_farm_image...,yes,2021-11-19 08:58:47,FA0002,H01,1,3.0,7739.0,1708.6,success
4,FA0002_GW01_H01_0001_20211119092856_farm_image...,yes,2021-11-19 09:28:56,FA0002,H01,1,3.0,9148.0,2025.3,success
...,...,...,...,...,...,...,...,...,...,...
1388,FA0002_GW01_H02_0015_20211125145036_farm_image...,no,2021-11-25 14:50:36,FA0002,H02,15,3.0,9077.0,2009.4,success
1389,FA0002_GW01_H02_0015_20211125151240_farm_image...,no,2021-11-25 15:12:40,FA0002,H02,15,6.0,10136.0,2247.4,success
1390,FA0002_GW01_H02_0015_20211125152240_farm_image...,no,2021-11-25 15:22:40,FA0002,H02,15,3.0,10135.0,2247.2,success
1391,FA0002_GW01_H02_0015_20211125153515_farm_image...,no,2021-11-25 15:35:15,FA0002,H02,15,8.0,9413.0,2084.9,success
1392,FA0002_GW01_H02_0015_20211125154639_farm_image...,no,2021-11-25 15:46:39,FA0002,H02,15,2.0,10794.0,2395.4,success

In [136]:
target_date1 = '2021-11-24'
target_date2 = '2021-11-26'
df_db_20 = df_db.query('@target_date1 < create_time <  @target_date2')

In [138]:
df_db_20.groupby(pd.Grouper(key='bright')).mean()

,module_id,weight_prediction_count,weight_prediction_pixel_mean,weight_prediction_weight
bright,,,,
yes,9.598018,3.129956,9079.093612,2009.858370
no,8.265979,2.688660,9368.622680,2074.942887

### 11월 26 ~ 11월 30 평균 픽셀

In [5]:
# pixel 데이터 로드
df_jetson = pd.read_csv("./csv/11_26~11_30.csv")
df_jetson.shape
df_jetson

,date,org_file_name,weight_prediction_pixel_mean,weight_prediction_weight,bright
0,20211130090854,FA0002_GW01_H02_0010_20211130090854_farm_image...,7950.00,1788.0,yes
1,20211130091037,FA0002_GW01_H01_0002_20211130091037_farm_image...,10900.00,2455.7,yes
2,20211130113445,FA0002_GW01_H02_0015_20211130113445_farm_image...,9362.50,2107.7,no
3,20211130140626,FA0002_GW01_H02_0012_20211130140626_farm_image...,8337.50,1875.7,yes
4,20211130092038,FA0002_GW01_H02_0013_20211130092038_farm_image...,10618.75,2392.1,yes
...,...,...,...,...,...
1279,20211129122238,FA0002_GW01_H02_0010_20211129122238_farm_image...,10393.75,2341.1,yes
1280,20211129114840,FA0002_GW01_H02_0010_20211129114840_farm_image...,9737.50,2192.6,yes
1281,20211129123642,FA0002_GW01_H02_0014_20211129123642_farm_image...,12400.00,2795.3,yes
1282,20211129084049,FA0002_GW01_H02_0013_20211129084049_farm_image...,8912.50,2005.8,yes
1283,20211129134228,FA0002_GW01_H01_0002_20211129134228_farm_image...,11787.50,2656.6,yes

In [21]:
# drop null
df_jetson = df_jetson[~df_jetson.weight_prediction_pixel_mean.isnull()]
df_jetson['date'] = df_jetson['date'].astype(str)
df_jetson['date'] = pd.to_datetime(df_jetson['date'])

target_day = 30
df_jetson_30 = df_jetson.query('date.dt.day == @target_day')

In [22]:
df_jetson_30.groupby(pd.Grouper(key='bright')).mean()

        weight_prediction_pixel_mean  weight_prediction_weight
bright
yes                     10161.141304               2288.478261
no                      10204.907025               2298.385950